version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}deploytest
    build:
      context: .
      dockerfile: DeployTest/Dockerfile

  client:
    image: client
    build:
        context: ./example-client
        dockerfile: Dockerfile

  proxy:
    image: nginx:mainline

