version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+5000:83
    ports:
      - "5000:83"
      #- "443" 
    #volumes:   
    #  - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #  - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  client:
    ports:
        - "5001:3000"
  
  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
        - "83:83"    
